CC = gcc
CFLAGS = -Wall -Wextra -O2

# Paths
SDK_DIR = sdk
GAME_DIR = game_target
CHEAT_DIR = cheat
DAEMON_DIR = quark_daemon
BPF_VMLINUX = $(DAEMON_DIR)/src/bpf/vmlinux.h

.PHONY: all daemon vmlinux game cheat kernel kernel-testing clean

all: daemon game cheat

daemon: $(DAEMON_DIR)/quark_cli $(BPF_VMLINUX)
	@echo "=== Compiling Quark Daemon (Rust) ==="
	cargo build --release --manifest-path $(DAEMON_DIR)/Cargo.toml

# Kernel type definitions for the daemon's BPF-LSM/telemetry programs
# (quark_daemon/src/bpf/quark.bpf.c), dumped from the build host's BTF. CO-RE
# relocations let the resulting object load on other kernels too, so this only
# needs regenerating if the BPF code starts using types this kernel lacks.
# Not committed (.gitignore): ~160k lines and host-specific.
vmlinux: $(BPF_VMLINUX)

$(BPF_VMLINUX):
	@echo "=== Generating vmlinux.h from /sys/kernel/btf/vmlinux ==="
	bpftool btf dump file /sys/kernel/btf/vmlinux format c > $@

# quark_cli signs every protect/unprotect request with the testing private key
# (tooling/keys/generate-testing-key.sh) -- needs OpenSSL's libcrypto.
$(DAEMON_DIR)/quark_cli: $(DAEMON_DIR)/quark_cli.c
	@echo "=== Compiling Quark Netlink CLI Client (C) ==="
	$(CC) $(CFLAGS) $(DAEMON_DIR)/quark_cli.c -o $(DAEMON_DIR)/quark_cli -lcrypto

game: $(GAME_DIR)/game.c $(SDK_DIR)/quark_sdk.c
	@echo "=== Compiling Game & SDK (C) ==="
	$(CC) $(CFLAGS) -I$(SDK_DIR) $(GAME_DIR)/game.c $(SDK_DIR)/quark_sdk.c -o $(GAME_DIR)/game

cheat: $(CHEAT_DIR)/cheat.c
	@echo "=== Compiling Cheat (C) ==="
	$(CC) $(CFLAGS) $(CHEAT_DIR)/cheat.c -o $(CHEAT_DIR)/cheat

# Expected SHA-256 of the real quark_cli binary, embedded in the kernel module so it
# can tell "root process running the genuine quark_cli" apart from "some other root
# process" (kernel/quark_kernel.c's quark_check_sender). Regenerated on every build
# from whatever quark_cli was actually just compiled -- not committed (.gitignore).
kernel/quark_cli_hash.h: $(DAEMON_DIR)/quark_cli
	@echo "=== Generating expected quark_cli hash for kernel module ==="
	@printf '/* Auto-generated by the top-level Makefile -- DO NOT hand-edit. */\n#ifndef QUARK_CLI_HASH_H\n#define QUARK_CLI_HASH_H\nstatic const unsigned char quark_cli_expected_sha256[32] = {%s};\n#endif\n' \
	  "$$(sha256sum $(DAEMON_DIR)/quark_cli | cut -d' ' -f1 | sed 's/../0x&,/g')" \
	  > kernel/quark_cli_hash.h

# Release kernel module: refuses to protect anything inside a VM, no bypass compiled in.
kernel: kernel/quark_cli_hash.h
	@echo "=== Compiling Quark Kernel Module (release) ==="
	make -C kernel

# Testing kernel module: VM check is bypassed, since this project's own VM test rig is
# itself a hypervisor guest. Never intended for a real release.
kernel-testing: kernel/quark_cli_hash.h
	@echo "=== Compiling Quark Kernel Module (testing, VM check bypassed) ==="
	make -C kernel testing

clean:
	@echo "=== Cleaning Build Artifacts ==="
	cargo clean --manifest-path $(DAEMON_DIR)/Cargo.toml
	rm -f $(DAEMON_DIR)/quark_cli
	rm -f $(GAME_DIR)/game
	rm -f $(CHEAT_DIR)/cheat
	rm -f kernel/quark_cli_hash.h
	rm -f $(BPF_VMLINUX)
	rm -f /tmp/quark.sock
	make -C kernel clean
