#!/bin/bash
# Generates a TESTING-ONLY ECDSA P-256 keypair used to sign Quark's netlink control
# messages (kernel module <-> quark_cli), so the kernel module only honors
# protect/unprotect requests actually signed by the real quark_cli, not just anything
# that opens a netlink socket to protocol 31 (see docs/vm_test_environment.md).
#
# This key is NOT suitable for a real release -- it has no secure storage, rotation,
# or distribution story, just a root-only-readable PEM file on disk. It exists so this
# project's own dev/test rig can exercise the signing path end to end.
#
# Usage: tooling/keys/generate-testing-key.sh [output-dir]
#   output-dir defaults to tooling/keys/ (private key stays out of git -- see .gitignore)
#
# Regenerates kernel/quark_pubkey.h (safe to commit -- it's the PUBLIC key) with the
# raw 65-byte SEC1 uncompressed point the kernel module embeds and verifies against.
# The matching private key must be installed at /opt/quark-anticheat/keys/
# quark_signing_key.pem (0600, root-only) wherever quark_cli actually runs.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../.."

OUT_DIR="${1:-tooling/keys}"
mkdir -p "$OUT_DIR"

PRIV="$OUT_DIR/quark_signing_key.pem"
PUB_DER="$OUT_DIR/quark_signing_key_pub.der"
HEADER="kernel/quark_pubkey.h"

echo "=== Generating testing-only ECDSA P-256 keypair ==="
openssl ecparam -name prime256v1 -genkey -noout -out "$PRIV"
chmod 600 "$PRIV"
openssl ec -in "$PRIV" -pubout -outform DER -out "$PUB_DER" 2>/dev/null

# The DER SubjectPublicKeyInfo for a P-256 key is a fixed 26-byte header followed by
# the raw 65-byte SEC1 uncompressed point (0x04 || X || Y) -- confirmed against this
# project's kernel (crypto_sig_set_pubkey for "x962(ecdsa-nist-p256)" wants exactly
# that raw point, not the full SPKI DER).
POINT_HEX=$(tail -c 65 "$PUB_DER" | xxd -p -c 65)

{
    echo "/* Auto-generated by tooling/keys/generate-testing-key.sh -- DO NOT hand-edit."
    echo " * Public key only -- safe to commit. The matching private key is generated"
    echo " * alongside this script's output and must never be committed (see .gitignore)."
    echo " */"
    echo "#ifndef QUARK_PUBKEY_H"
    echo "#define QUARK_PUBKEY_H"
    echo
    echo "/* Raw SEC1 uncompressed ECDSA P-256 public key point (0x04 || X || Y). */"
    echo -n "static const unsigned char quark_pubkey[65] = {"
    echo -n "$POINT_HEX" | sed 's/../0x&,/g;s/,$//'
    echo "};"
    echo
    echo "#endif /* QUARK_PUBKEY_H */"
} > "$HEADER"

rm -f "$PUB_DER"

echo "Private key: $PRIV (0600, NOT committed -- install to"
echo "  /opt/quark-anticheat/keys/quark_signing_key.pem on whichever box runs quark_cli)"
echo "Public key header regenerated: $HEADER (commit this)"
